services:
  db:
    image: postgres:15.3
    container_name: imss_telegram_bot_db
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: diego
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: imss_telegram_bot_db
    volumes:
      - ./postgres:/var/lib/postgresql/data

  app:
    container_name: imss_telegram_bot_app
    restart: unless-stopped
    image: node:trixie-slim
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run prisma:generate && npm run build && npm start"
    volumes:
      - ./:/usr/src/app
    environment:
      - BOT_TOKEN
      - PSQL_CONNECTION_STRING
      - GEMINI_API_KEY
    depends_on:
      - db
